### ISSUE TITLE
photoprism image tag format changed

### ISSUE THREAD

**Issue by ammmze** [Diaoul/home-ops#2904]
FYI ... While setting up photoprism in my cluster, I was browsing others and noticed that the image tag format changed from what you've got (`20220121`) and renovate doesn't seem to pick up on the new versions. It is now in the format of `YYMMDD-distro` (i.e. `220517-bullseye`).

**Comment by Diaoul** [comment]
Oh thank you for reporting that to me that's very kind. Totally missed it :pray: Fixed with 6a337ce9cda230f5215b368a1a946163684a1478 :+1:
